# This is a basic workflow to help you get started with Actions

name: LuaDoc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-lua-doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Clone wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki
      - name: Parse and generate documentation
        uses: p3lim/lua-doc-parser@v2
        with:
          output: .wiki
      - name: Push wiki changes
        working-directory: .wiki
        run: |
          git config user.name CI
          git config user.email "<>"
          git add .
          git diff --quiet HEAD || git commit -m "$GITHUB_SHA"
          git push
